name = "JETTest"
uuid = "a79fb612-4a80-4749-a9bd-c2faab13da61"
authors = ["Shuhei Kadowaki <aviatesk@gmail.com> and contributors"]
version = "0.1.4"

[deps]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"

[compat]
JET = "0.5.0"
MacroTools = "0.5.6"
julia = "1.6"

[extras]
MacroTools = "1914dd2f-81c6-5fcd-8719-6d5c9610ff09"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["MacroTools", "Test"]
